stages:
  - destroy
  - docker
  - test
  - validate
  - plan
  - apply

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"


cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${CI_PROJECT_DIR}/services/example-application-service/.venv/

build-python-ci-image:
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  stage: docker
  before_script:
    - cd ci_cd/python/
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t registry.gitlab.com/nirooma/fastapi-services:cicd-python3.9-slim .
    - docker push registry.gitlab.com/nirooma/fastapi-services:cicd-python3.9-slim
  only:
    changes:
      - ci_cd/python/Dockerfile
    refs:
      - master

build-docker-ci-image:
  image: docker:19.03
  services:
    - docker:19.03-dind
  stage: docker
  before_script:
    - cd ci_cd/docker/
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t registry.gitlab.com/nirooma/fastapi-services:cicd-docker .
    - docker push registry.gitlab.com/nirooma/fastapi-services:cicd-docker
  only:
    changes:
      - ci_cd/docker/Dockerfile
    refs:
      - master

include:
  - local: /services/example-application-service/ci-cd.yml
  - local: /infrastructure/global/vpc/ci-cd.yml
  - local: /infrastructure/example-application-service/ci-cd.yml