version: '3.8'
services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  web:
    build: ./services/example-application-service
    container_name: backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./services/example-application-service:/opt/donatello
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: