version: '3.3'


services:
  leonardo-db:
    image: postgres:13.4-alpine
    container_name: leonardo-db
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      retries: 5
    restart: always


  leonardo:
    build: ./services/leonardo
    container_name: leonardo
    command: daphne --bind 0.0.0.0 --port 8002 core.asgi:application
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: fastapi
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_HOST: leonardo-db
      SQL_PORT: 5432
#    entrypoint: ./entrypoint
    depends_on:
      - leonardo-db
    volumes:
      - staticfiles_:/opt/leonardo/staticfiles
    expose:
      - 8002

  nginx:
    build: ./infrastructure/nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - leonardo

    restart: always
    volumes:
      - staticfiles_:/opt/leonardo/staticfiles

volumes:
  staticfiles_:
