cache:
  key: talk-booking-service-environment
  paths:
    - ${CI_PROJECT_DIR}/infrastructure/example-application-service/development/.terraform

.example-application-service-validate:
  image: registry.gitlab.com/gitlab-org/terraform-images/releases/0.14:v0.10.0
  stage: validate
  before_script:
    - cd ${TF_ROOT}
  script:
    - gitlab-terraform init -var="vpc_state_username=gitlab-ci-token" -var="vpc_state_password=$CI_JOB_TOKEN"
    - gitlab-terraform validate -var="vpc_state_username=gitlab-ci-token" -var="vpc_state_password=$CI_JOB_TOKEN"

example-application-service-validate-development:
  extends: .example-application-service-validate
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/infrastructure/example-application-service/development
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/example-application-service-development
  only:
    refs:
      - merge_requests
      - master
    changes:
      - infrastructure/example-application-service/development/**/*
      - infrastructure/modules/example-application-service/**/*

.example-application-service-plan:
  image: registry.gitlab.com/gitlab-org/terraform-images/releases/0.14:v0.10.0
  stage: plan
  before_script:
    - cd ${TF_ROOT}
  script:
    - gitlab-terraform plan -var="vpc_state_username=gitlab-ci-token" -var="vpc_state_password=$CI_JOB_TOKEN"
    - gitlab-terraform plan-json -var="vpc_state_username=gitlab-ci-token" -var="vpc_state_password=$CI_JOB_TOKEN"
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

example-application-service-plan-development:
  extends: .example-application-service-plan
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/infrastructure/example-application-service/development
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/example-application-service-development
  only:
    refs:
      - merge_requests
      - master
    changes:
      - infrastructure/example-application-service/development/**/*
      - infrastructure/modules/example-application-service/**/*

.example-application-service-apply:
  image: registry.gitlab.com/gitlab-org/terraform-images/releases/0.14:v0.10.0
  stage: apply
  before_script:
    - cd ${TF_ROOT}
  script:
    - gitlab-terraform apply
  when: manual

example-application-service-apply-development:
  extends: .example-application-service-apply
  environment:
    name: development
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/infrastructure/example-application-service/development
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/example-application-service-development
  dependencies:
    - example-application-service-plan-development
  only:
    refs:
      - master
    changes:
      - infrastructure/example-application-service/development/**/*
      - infrastructure/modules/example-application-service/**/*