apiVersion: apps/v1
kind: Deployment
metadata:
  name: splinter-depl
  labels:
    app: splinter
spec:
  replicas: 1
  template:
    metadata:
      name: splinter
      labels:
        app: splinter
    spec:
      containers:
        - name: splinter
          image: nirooma/splinter:main
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: splinter

---

apiVersion: v1
kind: Service
metadata:
  name: splinter-svc
spec:
  selector:
    app: splinter
  ports:
    - port: 3000
  type: NodePort