# client/Dockerfile

# pull official base image
FROM node:15.4.0-alpine
ENV HOME /opt/splinter
# set working directory
WORKDIR $HOME

# add `$HOME/node_modules/.bin` to $PATH
ENV PATH $HOME/node_modules/.bin:$PATH

# install app dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install --production

# copy project
COPY . .