name: Michelangelo Workflow

on:
  push:
    branches: [ main, release/** ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'services/michelangelo/**'
      - '.github/workflows/michelangelo.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        uses: Gr1N/setup-poetry@v7
        run: |
          poetry add pylint

      - name: Analysing the code with pylint
        run: |
          poetry run pylint `ls -R|grep .py$|xargs`

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.MICHALANGELO_IMAGE_NAME_IN_DOCKERHUB }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: services/michelangelo
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
