name: Building Michelangelo Workflow

on:
  push:
    branches:  [ main ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'services/michelangelo/**'
      - '.github/workflows/michelangelo.yaml'

env:
  DOCKER_BUILDKIT: 1
  MICHALANGELO_IMAGE_NAME_IN_DOCKERHUB: ${{ secrets.MICHALANGELO_IMAGE_NAME_IN_DOCKERHUB }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: Meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.MICHALANGELO_IMAGE_NAME_IN_DOCKERHUB }}

      - name: Test Outputs
        run: |
            echo ${{ steps.Meta.outputs.tags }}
            echo ${{ steps.meta.outputs.labels }}
